name: smdh
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/phoenixr-codes/smdh

environment:
  sdk: ^3.5.1

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
